# Generated by Django 5.2.1 on 2025-05-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='upddated',
            new_name='updated',
        ),
    ]
